### ISSUE TITLE
Python 3.5

### ISSUE THREAD

**Issue by damontallen** [ritchie46/structural_engineering#7]
@ritchie46 what breaks with Python 3.5?

**Comment by ritchie46** [comment]
Hi Damon,

What do you mean with 'breaks'?  I wrote the code in  3.5.

**Comment by damontallen** [comment]
Sorry, I miss read your setup file.


Regards,
Damon

Damon T. Allen Ph.D.
Adjunct Professor
(352) 234-3266
damontallen@gmail.com
344 Rinker Hall
School of Construction Management
University of Florida

**Comment by damontallen** [comment]
@ritchie46 By the way, I really like your work here.  Are you attending JupyterDay in Atlanta on the 13th?

**Comment by ritchie46** [comment]
@damontallen Thanks! Jupyter notebook is also what I've had in mind for this.

Well.. I live in the Netherlands, so I guess I'll have to wait for the Youtube videos.
